name: Base pipelines

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:

    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
        
    - name: Copy Environment variables
      run: cp .env.example .env

    - name: Load composer packages
      run: composer.phar install

    - name: "Remove var directory"
      run: rm -rf var
    
    - name: Run php-cs-fixer
      run: vendor/bin/php-cs-fixer --config=.php-cs-fixer.dist.php fix --dry-run .

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Build app container
      run: docker build . -t  pipeline_app -f ./docker/app/Dockerfile
    
    - name: Build nginx container
      run: docker build . -t pipeline_nginx -f ./docker/nginx/Dockerfile
