name: Balancer CI-CD pipelines

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:

    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
        
    - name: Copy Environment variables
      run: cp .env.example .env
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Build app container
      run: docker build . -t balancer_app -f ./docker/app/Dockerfile
    
    - name: Build nginx container
      run: docker build . -t balancer_web -f ./docker/nginx/Dockerfile
